spring.application.name=phishing-scanner

phishing-scanner.phone-number=48123123123

uri-verifier.base-url=https://webrisk.googleapis.com
uri-verifier.evaluate-uri=/v1eap1:evaluateUri
uri-verifier.access-token=token

logging.level.pl.tk.phishingscanner=TRACE

spring.datasource.url=jdbc:h2:mem:db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.cloud.function.definition=textMessageConsumer

spring.cloud.stream.bindings.textMessageConsumer-in-0.destination=new-message
spring.cloud.stream.bindings.textMessageConsumer-in-0.binder=rabbit
spring.cloud.stream.bindings.textMessageConsumer-in-0.group=new-message-group
spring.cloud.stream.bindings.textMessageConsumer-in-0.error-handler-definition=textMessageErrorConsumer
spring.cloud.stream.bindings.textMessageConsumer-in-0.content-type=application/json

spring.cloud.stream.bindings.phishing-messages-out-0.destination=phishing-messages
spring.cloud.stream.bindings.phishing-messages-out-0.binder=rabbit
spring.cloud.stream.bindings.phishing-messages-out-0.content-type=application/json

spring.cloud.stream.bindings.safe-messages-out-0.destination=safe-messages
spring.cloud.stream.bindings.safe-messages-out-0.binder=rabbit
spring.cloud.stream.bindings.safe-messages-out-0.content-type=application/json
