spring.application.name=phishing-scanner

uri-verifier.base-url=https://webrisk.googleapis.com
uri-verifier.evaluate-uri=/v1eap1:evaluateUri
uri-verifier.access-token=token

logging.level.pl.tk.phishingscanner=TRACE